# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: false
enable_free_tier: true

reviews:
  profile: chill
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  review_status: true
  commit_status: true
  request_changes_workflow: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "src/**"
    - "public/**"
    - "webpack.config.cjs"
    - "package.json"
    - "package-lock.json"
    - "tsconfig*.json"
    - ".github/**"
    - "!dist/**"
    - "!node_modules/**"

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
