import hljs from 'highlight.js/lib/core'
// Slimmed-down language pack: highlight.js/lib/common ships ~40 languages.
// The messenger only needs the mainstream snippet languages; highlightAuto()
// degrades gracefully to the closest registered language (or plain text via
// the try/catch fallbacks below), so shrinking the set never breaks rendering.
import bash from 'highlight.js/lib/languages/bash'
import c from 'highlight.js/lib/languages/c'
import cpp from 'highlight.js/lib/languages/cpp'
import csharp from 'highlight.js/lib/languages/csharp'
import css from 'highlight.js/lib/languages/css'
import diff from 'highlight.js/lib/languages/diff'
import go from 'highlight.js/lib/languages/go'
import ini from 'highlight.js/lib/languages/ini'
import java from 'highlight.js/lib/languages/java'
import javascript from 'highlight.js/lib/languages/javascript'
import json from 'highlight.js/lib/languages/json'
import markdown from 'highlight.js/lib/languages/markdown'
import php from 'highlight.js/lib/languages/php'
import python from 'highlight.js/lib/languages/python'
import rust from 'highlight.js/lib/languages/rust'
import scss from 'highlight.js/lib/languages/scss'
import shell from 'highlight.js/lib/languages/shell'
import sql from 'highlight.js/lib/languages/sql'
import typescript from 'highlight.js/lib/languages/typescript'
import xml from 'highlight.js/lib/languages/xml'
import yaml from 'highlight.js/lib/languages/yaml'

hljs.registerLanguage('bash', bash)
hljs.registerLanguage('c', c)
hljs.registerLanguage('cpp', cpp)
hljs.registerLanguage('csharp', csharp)
hljs.registerLanguage('css', css)
hljs.registerLanguage('diff', diff)
hljs.registerLanguage('go', go)
hljs.registerLanguage('ini', ini)
hljs.registerLanguage('java', java)
hljs.registerLanguage('javascript', javascript)
hljs.registerLanguage('json', json)
hljs.registerLanguage('markdown', markdown)
hljs.registerLanguage('php', php)
hljs.registerLanguage('python', python)
hljs.registerLanguage('rust', rust)
hljs.registerLanguage('scss', scss)
hljs.registerLanguage('shell', shell)
hljs.registerLanguage('sql', sql)
hljs.registerLanguage('typescript', typescript)
hljs.registerLanguage('xml', xml)
hljs.registerLanguage('yaml', yaml)
import { isComboxUrl, toCurrentOriginComboxUrl } from '../components/chat/chatUtils'

/**
 * Message formatting engine (Telegram-modern parity + standard markdown).
 *
 * Delimiter cheatsheet (documented choice, `__` cannot be both bold and underline):
 *   **bold**   <strong>
 *   __underline__   <u>          (Telegram style: `__` is underline, never bold)
 *   *italic* / _italic_   <em>
 *   ~~strike~~   <s>
 *   ||spoiler||   <span class="mbSpoiler">   (click to reveal)
 *   `inline code`   <code class="mbCode">
 *   [label](https://url)   <a class="mbLink">
 *   @username / bare URLs   autolinked (same regexes as before)
 *
 * Block level:
 *   ```lang ... ```   code block (auto-detect when no language)
 *   > line            blockquote (consecutive lines are grouped)
 *   >>> line >>>      multi-line quote (Telegram style)
 *   - item / 1. item  unordered / ordered list
 *   # .. ######       headings
 *   --- / ***         horizontal rule
 *
 * Safety: every byte of user text is HTML-escaped before it is emitted; only
 * tags generated by this module ever reach the DOM. No user HTML is allowed.
 */

export interface RenderMessageOptions {
  /** Accessible label for the "copy" button on code blocks. */
  copyLabel?: string
}

/** Guard against pathological nested inline recursion. */
const MAX_INLINE_DEPTH = 24

const ESCAPABLE_RE = /[!"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]/
const PUNCT_RE = /[!-/:-@[-`{-~\u00A1-\u00BF\u2010-\u2027\u2030-\u205E]/
const SAFE_HREF_RE = /^(https?:\/\/|mailto:)/i
const LANG_NAME_RE = /^[A-Za-z0-9_+#.-]+$/
const TRAILING_HASH_RE = /[ \t]+#+[ \t]*$/

const FENCE_CLOSE_RE = /^[ \t]*(`{3,}|~{3,})[ \t]*$/
const HR_RE = /^[ \t]{0,3}(-{3,}|\*{3,}|_{3,})[ \t]*$/
const HEADING_RE = /^[ \t]{0,3}(#{1,6})[ \t]+(\S.*?)[ \t]*$/
const QUOTE_MULTI_RE = /^[ \t]{0,3}>>>[ \t]?(.*)$/
const QUOTE_RE = /^[ \t]{0,3}>[ \t]?(.*)$/
const LIST_U_RE = /^[ \t]{0,3}[-*+][ \t]+(.*)$/
const LIST_O_RE = /^[ \t]{0,3}\d{1,9}[.)][ \t]+(.*)$/

interface ParsedLink {
  label: string
  url: string
  end: number
}

interface CodeSpan {
  content: string
  end: number
}

type Block =
  | { kind: 'code'; lang: string; code: string; gap: number }
  | { kind: 'quote'; lines: string[]; gap: number }
  | { kind: 'list'; ordered: boolean; items: string[]; gap: number }
  | { kind: 'heading'; level: number; text: string; gap: number }
  | { kind: 'hr'; gap: number }
  | { kind: 'para'; lines: string[]; gap: number }

/** Escapes user text so it can never be interpreted as HTML. */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function escapeWithBreaks(text: string): string {
  return escapeHtml(text).replace(/\n/g, '<br>')
}

function isEscapable(ch: string): boolean {
  return ESCAPABLE_RE.test(ch)
}

function runLength(src: string, start: number, ch: string): number {
  let i = start
  while (i < src.length && src[i] === ch) i += 1
  return i - start
}

interface Flanking {
  leftFlanking: boolean
  rightFlanking: boolean
  beforePunct: boolean
  afterPunct: boolean
}

/**
 * CommonMark-ish flanking rules. These are what keep `snake_case_names` and
 * `some_var` from being turned into emphasis.
 */
function flanking(src: string, start: number, len: number): Flanking {
  const beforeEnd = start
  const afterStart = start + len
  const prev = beforeEnd > 0 ? src[beforeEnd - 1] : ''
  const next = afterStart < src.length ? src[afterStart] : ''
  const beforeWs = beforeEnd === 0 || /\s/.test(prev)
  const afterWs = afterStart >= src.length || /\s/.test(next)
  const beforePunct = beforeEnd > 0 && PUNCT_RE.test(prev)
  const afterPunct = afterStart < src.length && PUNCT_RE.test(next)
  const leftFlanking = !afterWs && (!afterPunct || beforeWs || beforePunct)
  const rightFlanking = !beforeWs && (!beforePunct || afterWs || afterPunct)
  return { leftFlanking, rightFlanking, beforePunct, afterPunct }
}

function canOpen(src: string, start: number, len: number, ch: string): boolean {
  const f = flanking(src, start, len)
  if (ch === '_') return f.leftFlanking && (!f.rightFlanking || f.beforePunct)
  return f.leftFlanking
}

function canClose(src: string, start: number, len: number, ch: string): boolean {
  const f = flanking(src, start, len)
  if (ch === '_') return f.rightFlanking && (!f.leftFlanking || f.afterPunct)
  return f.rightFlanking
}

/** Reads a `code span` starting at `start`. Returns null when unclosed. */
function readCodeSpan(src: string, start: number): CodeSpan | null {
  const len = runLength(src, start, '`')
  let i = start + len
  while (i < src.length) {
    if (src[i] === '`') {
      const run = runLength(src, i, '`')
      if (run === len) {
        return { content: src.slice(start + len, i).replace(/\n/g, ' '), end: i + run }
      }
      i += run
      continue
    }
    i += 1
  }
  return null
}

/** Reads `[label](url)` starting at `start`. Returns null when malformed. */
function readLink(src: string, start: number): ParsedLink | null {
  if (src[start] !== '[') return null
  let i = start + 1
  let depth = 1
  let labelEnd = -1
  while (i < src.length) {
    const c = src[i]
    if (c === '\\' && i + 1 < src.length) {
      i += 2
      continue
    }
    if (c === '[') depth += 1
    else if (c === ']') {
      depth -= 1
      if (depth === 0) {
        labelEnd = i
        break
      }
    }
    i += 1
  }
  if (labelEnd < 0) return null
  if (src[labelEnd + 1] !== '(') return null
  let j = labelEnd + 2
  let parens = 1
  let urlEnd = -1
  while (j < src.length) {
    const c = src[j]
    if (c === '\\' && j + 1 < src.length) {
      j += 2
      continue
    }
    if (c === '(') parens += 1
    else if (c === ')') {
      parens -= 1
      if (parens === 0) {
        urlEnd = j
        break
      }
    } else if (c === '\n') return null
    j += 1
  }
  if (urlEnd < 0) return null
  const label = src.slice(start + 1, labelEnd)
  const url = src.slice(labelEnd + 2, urlEnd).trim()
  if (!url || /\s/.test(url)) return null
  return { label, url, end: urlEnd + 1 }
}

interface FenceInfo {
  marker: string
  info: string
}

/** Opening code fence of a line, or null when the line is not a fence. */
function matchFenceOpen(line: string): FenceInfo | null {
  const m = /^[ \t]*(`{3,}|~{3,})[ \t]*(\S*)/.exec(line)
  if (!m) return null
  const marker = m[1]
  const info = m[2] || ''
  // Backtick fences may not carry backticks in their info string.
  if (marker[0] === '`' && info.includes('`')) return null
  return { marker, info }
}

function isBlockStart(line: string): boolean {
  return (
    matchFenceOpen(line) !== null ||
    HR_RE.test(line) ||
    HEADING_RE.test(line) ||
    QUOTE_RE.test(line) ||
    LIST_U_RE.test(line) ||
    LIST_O_RE.test(line)
  )
}

function renderUrlAnchor(raw: string): string {
  const resolvedHref = /^https?:\/\//i.test(raw) ? raw : `https://${raw}`
  const combox = isComboxUrl(resolvedHref)
  const href = combox ? toCurrentOriginComboxUrl(resolvedHref) : resolvedHref
  const target = combox ? '_self' : '_blank'
  const rel = combox ? '' : ' rel="noreferrer noopener"'
  return `<a class="mbLink" href="${escapeHtml(href)}" target="${target}"${rel}>${escapeHtml(raw)}</a>`
}

/** Escapes a plain run of text and turns @username into a user reference. */
function renderNames(text: string, absStart: number): string {
  if (!text) return ''
  const re =
    absStart === 0
      ? /(^|[\s([{\u00A0>])@([a-zA-Z0-9_]{3,32})/g
      : /([\s([{\u00A0>])@([a-zA-Z0-9_]{3,32})/g
  let out = ''
  let last = 0
  for (const match of text.matchAll(re)) {
    const index = match.index ?? 0
    const prefix = match[1] || ''
    const at = index + prefix.length
    const username = match[2]
    out += escapeWithBreaks(text.slice(last, at))
    out += `<a class="mbUserRef" href="/@${username}" data-username="${username}" data-mention="${username}">@${username}</a>`
    last = at + 1 + username.length
  }
  out += escapeWithBreaks(text.slice(last))
  return out
}

/**
 * Escapes a raw run of text, autolinking bare URLs first (same regex as the
 * original renderer) and then @username mentions.
 */
function renderTextChunk(chunk: string, offset: number, allowAutoLink: boolean): string {
  if (!chunk) return ''
  if (!allowAutoLink) return escapeWithBreaks(chunk)
  let out = ''
  let last = 0
  const urlRe = /\b((?:https?:\/\/|www\.)[^\s<>"'`]+)\b/gi
  for (const match of chunk.matchAll(urlRe)) {
    const index = match.index ?? 0
    out += renderNames(chunk.slice(last, index), offset + last)
    out += renderUrlAnchor(match[1] || '')
    last = index + match[0].length
  }
  out += renderNames(chunk.slice(last), offset + last)
  return out
}

type EmphTag = 'strong' | 'em' | 'u' | 's' | 'spoiler'

type InlineNode =
  | { type: 'text'; value: string; start: number }
  | { type: 'code'; value: string }
  | { type: 'link'; label: string; url: string }
  | { type: 'delim'; ch: string; count: number; start: number; canOpen: boolean; canClose: boolean }
  | { type: 'emph'; tag: EmphTag; children: InlineNode[] }

function tagFor(ch: string, use: number): EmphTag {
  if (ch === '~') return 's'
  if (ch === '|') return 'spoiler'
  if (ch === '_') return use === 2 ? 'u' : 'em'
  return use === 2 ? 'strong' : 'em'
}

function wrapTag(tag: EmphTag, inner: string): string {
  if (tag === 'spoiler') return `<span class="mbSpoiler">${inner}</span>`
  return `<${tag}>${inner}</${tag}>`
}

/** How many delimiter characters a pair consumes, or null when they cannot pair. */
function pairingUse(ch: string, openerCount: number, closerCount: number): number | null {
  if (ch === '~' || ch === '|') {
    const use = Math.min(openerCount, closerCount)
    return use >= 2 ? use : null
  }
  if (openerCount >= 2 && closerCount >= 2) return 2
  return 1
}

/**
 * Splits raw inline text into nodes. Delimiter runs become `delim` nodes;
 * code spans, links and backslash escapes become atomic nodes so markdown
 * inside them is never interpreted.
 */
function tokenizeInline(src: string): InlineNode[] {
  const nodes: InlineNode[] = []
  const n = src.length
  let textStart = 0
  let i = 0

  const pushText = (end: number): void => {
    if (end > textStart) nodes.push({ type: 'text', value: src.slice(textStart, end), start: textStart })
    textStart = end
  }

  while (i < n) {
    const ch = src[i]

    if (ch === '\\' && i + 1 < n && isEscapable(src[i + 1])) {
      pushText(i)
      nodes.push({ type: 'text', value: src[i + 1], start: i + 1 })
      i += 2
      textStart = i
      continue
    }

    if (ch === '`') {
      const span = readCodeSpan(src, i)
      if (span) {
        pushText(i)
        nodes.push({ type: 'code', value: span.content })
        i = span.end
        textStart = i
        continue
      }
      i += runLength(src, i, '`')
      continue
    }

    if (ch === '[') {
      const link = readLink(src, i)
      if (link && SAFE_HREF_RE.test(link.url)) {
        pushText(i)
        nodes.push({ type: 'link', label: link.label, url: link.url })
        i = link.end
        textStart = i
        continue
      }
      i += 1
      continue
    }

    if (ch === '*' || ch === '_' || ch === '~' || ch === '|') {
      const count = runLength(src, i, ch)
      if ((ch === '~' || ch === '|') && count < 2) {
        i += count
        continue
      }
      const canOpenHere = canOpen(src, i, count, ch)
      const canCloseHere = canClose(src, i, count, ch)
      if (canOpenHere || canCloseHere) {
        pushText(i)
        nodes.push({ type: 'delim', ch, count, start: i, canOpen: canOpenHere, canClose: canCloseHere })
        i += count
        textStart = i
        continue
      }
      i += count
      continue
    }

    i += 1
  }

  pushText(n)
  return nodes
}

/**
 * Pairs delimiters the way CommonMark does: closers are consumed left to
 * right and each one claims the nearest unused opener of the same character.
 * That keeps nesting correct (`*a **b** c*`) and leaves every unpaired
 * delimiter to be rendered literally - never as a half-open tag.
 */
function pairDelimiters(nodes: InlineNode[]): InlineNode[] {
  let j = 0
  while (j < nodes.length) {
    const closer = nodes[j]
    if (closer.type !== 'delim' || !closer.canClose || closer.count <= 0) {
      j += 1
      continue
    }
    let i = j - 1
    while (i >= 0) {
      const candidate = nodes[i]
      if (candidate.type === 'delim' && candidate.ch === closer.ch && candidate.canOpen && candidate.count > 0) break
      i -= 1
    }
    if (i < 0) {
      j += 1
      continue
    }
    const opener = nodes[i]
    if (opener.type !== 'delim') {
      j += 1
      continue
    }
    const use = pairingUse(closer.ch, opener.count, closer.count)
    if (!use) {
      j += 1
      continue
    }
    opener.count -= use
    closer.count -= use
    const children = nodes.slice(i + 1, j)
    const replacement: InlineNode[] = []
    if (opener.count > 0) replacement.push(opener)
    replacement.push({ type: 'emph', tag: tagFor(closer.ch, use), children })
    const closerStays = closer.count > 0
    if (closerStays) replacement.push(closer)
    nodes.splice(i, j - i + 1, ...replacement)
    // A closer that still has characters left must be reconsidered against
    // any opener further left (this is what makes ***x*** nest properly).
    if (closerStays) {
      const closerIndex = opener.count > 0 ? i + 2 : i + 1
      j = closerIndex - 1
    } else {
      j = i + replacement.length - 1
    }
  }
  return nodes
}

/**
 * Leftover delimiters become plain text and neighbouring text runs are merged
 * back together, so autolinking sees whole words again (a URL containing an
 * underscore, for example, must stay in one piece).
 */
function normalizeNodes(nodes: InlineNode[]): InlineNode[] {
  const out: InlineNode[] = []
  for (const node of nodes) {
    const last = out[out.length - 1]
    if (node.type === 'delim') {
      const literal: InlineNode = { type: 'text', value: node.ch.repeat(node.count), start: node.start }
      if (last && last.type === 'text') last.value += literal.value
      else out.push(literal)
      continue
    }
    if (node.type === 'text' && last && last.type === 'text') {
      last.value += node.value
      continue
    }
    out.push(node)
  }
  return out
}

function renderNodes(nodes: InlineNode[], allowAutoLink: boolean, depth: number): string {
  let out = ''
  for (const node of nodes) {
    if (node.type === 'text') {
      out += renderTextChunk(node.value, node.start, allowAutoLink)
    } else if (node.type === 'code') {
      out += `<code class="mbCode">${escapeHtml(node.value)}</code>`
    } else if (node.type === 'link') {
      const label = renderInline(node.label, false, depth + 1)
      out += `<a class="mbLink" href="${escapeHtml(node.url)}" target="_blank" rel="noopener noreferrer">${label}</a>`
    } else if (node.type === 'emph') {
      const inner =
        depth >= MAX_INLINE_DEPTH
          ? renderNodes(node.children, allowAutoLink, depth)
          : renderNodes(node.children, allowAutoLink, depth + 1)
      out += wrapTag(node.tag, inner)
    }
  }
  return out
}

/**
 * Renders inline markdown to HTML. Everything that is not generated by this
 * function is passed through `escapeHtml` first.
 */
function renderInline(src: string, allowAutoLink: boolean, depth: number): string {
  if (!src) return ''
  if (depth > MAX_INLINE_DEPTH) return renderTextChunk(src, 0, allowAutoLink)
  const nodes = normalizeNodes(pairDelimiters(tokenizeInline(src)))
  return renderNodes(nodes, allowAutoLink, depth)
}

interface AutoDetect {
  language: string | null
  value: string
}

/**
 * Soft confidence floor for the `highlightAuto` fallback (chip only; the
 * colourised `value` is always kept).
 *
 * Rationale: with the 21-language subset a snippet that matches essentially
 * nothing scores 0-1 (plain words like `hi`/`x` score 0-1, `ls -la | grep foo`
 * scored 1 as bash, `{"a":1}` scored 2 as css). Real code that hits even one
 * keyword/pattern scores >= 2 (`SELECT * FROM users` scores 3 as sql,
 * `print("hello world")` scores 2). So `< 2` means "no real evidence" and the
 * chip would be a coin flip — hide it, keep the highlighting.
 */
const MIN_AUTO_RELEVANCE = 2
/** Snippets shorter than this must have a clear winner (see gap below). */
const SHORT_CODE_LEN = 30
/** Minimum top-minus-secondBest relevance gap for short snippets. */
const MIN_RELEVANCE_GAP = 1

/**
 * Cheap conservative pre-checks for frequent languages, run BEFORE
 * `highlightAuto` (which confuses short snippets, e.g. `print("hello world")`
 * was guessed as bash with relevance 2, tied with go).
 *
 * Every pattern requires language-specific syntax that other registered
 * languages don't share (colon-terminated `def/for/while`, `print(` outside
 * `<?php`, valid `JSON.parse`, `SELECT...FROM` pairs, ES `import...from "..."`,
 * line-anchored coreutils, `|`-into-classic-filter). Returns only canonical
 * names registered above, so `hljs.highlight` below never throws for an
 * unknown language (plus the `getLanguage` guard and try/catch anyway).
 */
function guessLanguageByHeuristics(code: string): string | null {
  const trimmed = code.trim()
  if (!trimmed) return null
  const firstLine = code.split('\n', 1)[0] ?? ''

  // 1. Shebang — the most explicit in-band signal.
  if (/^#!/.test(firstLine.trim())) {
    const sb = firstLine.toLowerCase()
    if (sb.includes('python')) return 'python'
    if (sb.includes('node') || sb.includes('deno') || sb.includes('bun')) return 'javascript'
    if (/\b(bash|sh|zsh|dash|ksh)\b/.test(sb)) return 'bash'
    return null
  }

  // 2. JSON — must actually parse, otherwise `{...}` could be JS/CSS.
  const head = trimmed[0]
  const tail = trimmed[trimmed.length - 1]
  if ((head === '{' && tail === '}') || (head === '[' && tail === ']')) {
    try {
      JSON.parse(trimmed)
      return 'json'
    } catch {
      // Not valid JSON — fall through to the other heuristics.
    }
  }

  // 3. SQL — require a statement keyword pair, never a lone word.
  if (
    /^\s*SELECT\b[\s\S]*\bFROM\b|^\s*INSERT\s+INTO\b|^\s*UPDATE\s+\S+\s+SET\b|^\s*DELETE\s+FROM\b|^\s*CREATE\s+(TABLE|INDEX|VIEW)\b|^\s*DROP\s+TABLE\b|^\s*ALTER\s+TABLE\b|^\s*WITH\s+\w+\s+AS\s*\(/im.test(
      code,
    )
  ) {
    return 'sql'
  }

  // 4. TypeScript-only declarations, before the generic JS checks.
  if (/^\s*(interface\s+\w+|type\s+\w+\s*=|enum\s+\w+)/m.test(code)) return 'typescript'

  // 5. JavaScript — ES import/export, console, function, arrow paired with a
  // JS keyword (bare `=>` alone could be PHP/Rust), CommonJS require().
  if (
    /^\s*import\s+.*\sfrom\s+['"]/m.test(code) ||
    /^\s*export\s+(default\s+)?(function|const|let|var|class|async)\b/m.test(code) ||
    /\bconsole\.(log|error|warn|info)\s*\(/.test(code) ||
    /^\s*function\s+\w*\s*\(/m.test(code) ||
    /\b(const|let|var)\b[^;\n]*=>/.test(code) ||
    (/=>/.test(code) && /\b(function|export|import)\b/.test(code)) ||
    /^\s*(const|let|var)\s+[\w${}[\]]+\s*=\s*require\s*\(/m.test(code)
  ) {
    return 'javascript'
  }

  // 6. Python — colon-terminated blocks and import forms no registered
  // language shares; `print(` is guarded against `<?php` only.
  if (
    /\bif\s+__name__\s*==/.test(code) ||
    /^\s*from\s+\S+\s+import\s+\S+/m.test(code) ||
    /^\s*import\s+[a-zA-Z_]\w*(\s*,\s*[a-zA-Z_]\w*)*(\s+as\s+[a-zA-Z_]\w*)?\s*(#.*)?$/m.test(code) ||
    /^\s*def\s+\w+\s*\(.*\)\s*(->\s*[\w[\], |.]+\s*)?:\s*(#.*)?$/m.test(code) ||
    /^\s*class\s+\w+(\s*\([^)]*\))?\s*:\s*(#.*)?$/m.test(code) ||
    /^\s*async\s+def\s+\w+\s*\(/m.test(code) ||
    /^\s*for\s+\S+\s+in\s+.+:\s*(#.*)?$/m.test(code) ||
    /^\s*(while|with|elif|except)\b.+:\s*(#.*)?$/m.test(code) ||
    /^\s*try\s*:\s*(#.*)?$/m.test(code) ||
    /^\s*if\b.+:\s*(#.*)?$/m.test(code)
  ) {
    return 'python'
  }
  if (!code.includes('<?php') && /\bprint\s*\(/.test(code)) return 'python'

  // 7. Shell — `$` prompt, line-anchored coreutils/package managers/CLIs
  // (anchored so `arr.find(` or `export default` can't match), classic pipes,
  // guarded `echo` (PHP `echo` ends with `;` or lives under `<?php`).
  if (
    /^\s*\$\s+\S+/m.test(code) ||
    /^\s*(ls(\s|$)|ll(\s|$)|pwd\b|cd\s+\S|mkdir\s|rmdir\s|rm\s|cp\s|mv\s|touch\s|cat\s|chmod\s|chown\s|grep\s|find\s|tar\s|curl\s|wget\s|ssh\s|scp\s|sudo\s|export\s+\w+=|source\s)/m.test(
      code,
    ) ||
    /^\s*(apt-get|apt|brew|yum|dnf|pacman)\s+\S+/m.test(code) ||
    /^\s*(docker|kubectl|npm|yarn|pnpm|pip3?|git)\s+\S+/m.test(code) ||
    /\|\s*(grep|sort|uniq|awk|sed|head|tail|wc|cut|xargs|less|more)\b/.test(code)
  ) {
    return 'bash'
  }
  if (/^\s*echo(\s+|$)/m.test(code) && !code.includes('<?php') && !trimmed.includes(';')) return 'bash'

  return null
}

/**
 * Language detection for code blocks without an explicit fence language.
 *
 * Order: conservative heuristics first (fix systemic `highlightAuto` misses
 * such as python `print()` guessed as bash), then `highlightAuto` as a
 * fallback with a soft confidence floor — a mizерная top-relevance
 * (`< MIN_AUTO_RELEVANCE`, i.e. no real keyword/pattern evidence) or a zero
 * gap to `secondBest` on a short snippet (`< SHORT_CODE_LEN`, a tie means a
 * coin flip) hides the chip but keeps the colourised output (`auto.value`).
 * An explicit fence language still wins in `renderCodeBlock` and never
 * reaches this path.
 */
function detectAuto(code: string): AutoDetect {
  const heuristic = guessLanguageByHeuristics(code)
  if (heuristic && hljs.getLanguage(heuristic)) {
    try {
      const highlighted = hljs.highlight(code, { language: heuristic, ignoreIllegals: true })
      return { language: highlighted.language || heuristic, value: highlighted.value }
    } catch {
      return { language: heuristic, value: escapeHtml(code) }
    }
  }
  try {
    const res = hljs.highlightAuto(code)
    const value = res.value || escapeHtml(code)
    const language = res.language || null
    if (!language) return { language: null, value }
    if ((res.relevance ?? 0) < MIN_AUTO_RELEVANCE) return { language: null, value }
    if (code.trim().length < SHORT_CODE_LEN) {
      const secondRelevance = res.secondBest?.relevance ?? 0
      if (res.relevance - secondRelevance < MIN_RELEVANCE_GAP) return { language: null, value }
    }
    return { language, value }
  } catch {
    return { language: null, value: escapeHtml(code) }
  }
}

/** Detects the language of `code`, or null when hljs has no guess. */
export function detectLanguage(code: string): string | null {
  return detectAuto(code).language
}

function renderCodeBlock(lang: string, code: string, options: RenderMessageOptions): string {
  let html = ''
  let chip = ''
  try {
    if (lang && hljs.getLanguage(lang)) {
      html = hljs.highlight(code, { language: lang, ignoreIllegals: true }).value
      chip = lang.toLowerCase()
    } else {
      const auto = detectAuto(code)
      html = auto.value
      chip = auto.language ? auto.language.toLowerCase() : ''
    }
  } catch {
    html = escapeHtml(code)
  }
  const label = escapeHtml(options.copyLabel || 'Copy code')
  const langChip = chip ? `<span class="mbCodeLang">${escapeHtml(chip)}</span>` : ''
  return (
    '<div class="mbCodeBlock">' +
    `<div class="mbCodeHead">${langChip}` +
    `<button type="button" class="mbCodeCopy" data-copy-code="1" title="${label}" aria-label="${label}">` +
    '<i class="mdi mdi-content-copy mbCodeCopyIcon" aria-hidden="true"></i>' +
    '</button></div>' +
    `<pre class="mbCodePre"><code class="hljs">${html}</code></pre>` +
    '</div>'
  )
}

function parseBlocks(text: string): Block[] {
  const lines = text.split('\n')
  const blocks: Block[] = []
  let blanks = 0
  let i = 0

  // Newlines between the previous block and this one, so the renderer can
  // keep the exact line spacing the raw text had.
  const nextGap = (): number => {
    const gap = blocks.length === 0 ? 0 : blanks + 1
    blanks = 0
    return gap
  }

  while (i < lines.length) {
    const line = lines[i]
    if (!line.trim()) {
      blanks += 1
      i += 1
      continue
    }

    const fence = matchFenceOpen(line)
    if (fence) {
      const body: string[] = []
      i += 1
      while (i < lines.length) {
        const close = FENCE_CLOSE_RE.exec(lines[i])
        if (close && close[1][0] === fence.marker[0] && close[1].length >= fence.marker.length) break
        body.push(lines[i])
        i += 1
      }
      if (i < lines.length) i += 1
      blocks.push({
        kind: 'code',
        lang: LANG_NAME_RE.test(fence.info) ? fence.info : '',
        code: body.join('\n'),
        gap: nextGap(),
      })
      continue
    }

    if (QUOTE_MULTI_RE.test(line)) {
      const body: string[] = []
      while (i < lines.length) {
        const m = QUOTE_MULTI_RE.exec(lines[i])
        if (!m) break
        body.push(m[1])
        i += 1
      }
      blocks.push({ kind: 'quote', lines: body, gap: nextGap() })
      continue
    }

    if (QUOTE_RE.test(line)) {
      const body: string[] = []
      while (i < lines.length) {
        const m = QUOTE_RE.exec(lines[i])
        if (!m) break
        body.push(m[1])
        i += 1
      }
      blocks.push({ kind: 'quote', lines: body, gap: nextGap() })
      continue
    }

    if (HR_RE.test(line)) {
      blocks.push({ kind: 'hr', gap: nextGap() })
      i += 1
      continue
    }

    const heading = HEADING_RE.exec(line)
    if (heading) {
      const content = heading[2].replace(TRAILING_HASH_RE, '').trim()
      blocks.push({ kind: 'heading', level: heading[1].length, text: content, gap: nextGap() })
      i += 1
      continue
    }

    const ordered = LIST_O_RE.exec(line)
    if (ordered || LIST_U_RE.test(line)) {
      const re = ordered ? LIST_O_RE : LIST_U_RE
      const items: string[] = []
      while (i < lines.length) {
        const m = re.exec(lines[i])
        if (!m) break
        items.push(m[1])
        i += 1
      }
      blocks.push({ kind: 'list', ordered: Boolean(ordered), items, gap: nextGap() })
      continue
    }

    const para: string[] = []
    while (i < lines.length && lines[i].trim() && !isBlockStart(lines[i])) {
      para.push(lines[i])
      i += 1
    }
    if (para.length) {
      blocks.push({ kind: 'para', lines: para, gap: nextGap() })
      continue
    }
    i += 1
  }

  return blocks
}

function renderBlock(block: Block, options: RenderMessageOptions): string {
  switch (block.kind) {
    case 'code':
      return renderCodeBlock(block.lang, block.code, options)
    case 'quote':
      return `<blockquote class="mbQuote">${block.lines.map((l) => renderInline(l, true, 0)).join('<br>')}</blockquote>`
    case 'list': {
      const tag = block.ordered ? 'ol' : 'ul'
      const cls = block.ordered ? 'mbList mbListOrdered' : 'mbList'
      const items = block.items.map((item) => `<li>${renderInline(item, true, 0)}</li>`).join('')
      return `<${tag} class="${cls}">${items}</${tag}>`
    }
    case 'heading': {
      const level = Math.min(6, Math.max(1, block.level))
      return `<h${level} class="mbHeading mbH${level}">${renderInline(block.text, true, 0)}</h${level}>`
    }
    case 'hr':
      return '<hr class="mbHr">'
    case 'para':
      return block.lines.map((l) => renderInline(l, true, 0)).join('<br>')
    default:
      return ''
  }
}

/**
 * Renders raw message text to safe HTML.
 *
 * The input is treated as untrusted: it is fully escaped and only markup
 * generated by this module is emitted.
 */
export function renderMessageHtml(text: string, options: RenderMessageOptions = {}): string {
  if (!text) return ''
  const blocks = parseBlocks(text.replace(/\r\n?/g, '\n'))
  let out = ''
  let previous: Block | null = null
  for (const block of blocks) {
    if (previous) {
      // Block elements start a line of their own, plain paragraphs do not, so
      // only the newline that separates two paragraphs has to become a <br>.
      const breaks = previous.kind === 'para' ? block.gap : Math.max(0, block.gap - 1)
      if (breaks > 0) out += '<br>'.repeat(breaks)
    }
    out += renderBlock(block, options)
    previous = block
  }
  return out
}
